version: '2'

services:
  mysql:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
  wordpress:
    image: wordpress
    volumes:
      - ./wordpress/:/var/www/html/wp-content
    ports:
      - 3000:80
    depends_on:
      - "mysql"
    environment:
      WORDPRESS_DB_PASSWORD: admin
  